name: SupeRSoniC-MIUI
on:
  workflow_dispatch:

env:
   CHATID: ${{ secrets.TG_CHAT_ID }}
   API_BOT: ${{ secrets.TG_TOKEN }}
   TYPE_KERNEL: ${{ secrets.NOVIK }}
         
jobs:
   build:
    runs-on: ubuntu-latest

    steps:
    - name: Setting Configurasi
      uses: actions/checkout@v3

    - name: Setup Initialize Environment
      run: |
           chmod +x initialize
           bash initialize
    - name: Starting For Building Your Kernel...
      run: |
           git clone --depth=1 https://github.com/vantoman/kernel_xiaomi_sm6150 -b 12.1 SONIC
           cp sonic-compiler.sh SONIC && cd SONIC
           chmod +x sonic-compiler.sh && bash sonic-compiler.sh
